import re
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent

MODULE_NAME = "breezeicons"

KOTLIN_FILE = (
    ROOT_DIR
    / MODULE_NAME
    / "src/main/java/com/github/migueldk17/breezeicons/icons/BreezeIcons.kt"
)
OUTPUT_FILE = (
    ROOT_DIR
    / MODULE_NAME
    / "src/main/java/com/github/migueldk17/breezeicons/icons/"
)

STYLES = [
    {
        "style": "Linear",
        "end": "object Outlined",
        "output": "LinearAll.generated.kt",
        "object_name": "BreezeIconsLinearAll"
    },
    {
        "style": "Outlined",
        "end": "object Colors",
        "output": "OutlinedAll.generated.kt",
        "object_name": "BreezeIconsOutlinedAll",
    },
    {
        "style": "Colors",
        "end": "}",
        "output": "ColorsAll.generated.kt",
        "object_name": "BreezeIconsColorsAll",
    }
]

if not KOTLIN_FILE.exists():
    raise FileNotFoundError(f"Arquivo não encontrado em: {KOTLIN_FILE}")

CATEGORY_REGEX = re.compile(r'object\s+(\w+)\s*\{')
ICON_REGEX = re.compile(r'val\s+(\w+)\s*:\s*BreezeIconsType')

def generate_all_for_style(style, end_maker, output_name, object_name):
    current_category = None
    icons = []
    inside_style = False

    
    lines = KOTLIN_FILE.read_text(encoding="utf-8").splitlines()

    for line in lines:
        if f"object {style}" in line:
            inside_style = True
            current_category = None
            continue

    
        if inside_style and end_maker in line:
            break
    
        if not inside_style:
            continue

        category_match = CATEGORY_REGEX.search(line)
        if category_match:
            current_category = category_match.group(1)
            continue

        icon_match = ICON_REGEX.search(line)
        if icon_match and current_category:
            icons.append((icon_match.group(1), current_category))

        icons.sort(key=lambda x: x[0])

        with OUTPUT_FILE.joinpath(output_name).open("w", encoding="utf-8") as f:
            f.write(
                f"""// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by script.py

package com.github.migueldk17.breezeicons.icons
import androidx.compose.runtime.Composable

    object {object_name} {{

    """
            )

            for icon, category in icons:
                f.write(
                    f"""        val {icon}
                @Composable
                get() = BreezeIcons.{style}.{category}.{icon}

    """
            )

            f.write("}\n")

        print(f"✔ Generated {len(icons)} icons in {output_name}")


for cfg in STYLES:
        generate_all_for_style(
            style=cfg["style"],
            end_maker=cfg["end"],
            output_name=cfg["output"],
            object_name=cfg["object_name"],
        )
