# -*- coding: utf-8 -*-
import re
import sys
from pathlib import Path


# -----------------------------
# Paths
# -----------------------------
ROOT_DIR = Path(__file__).resolve().parent.parent

MODULE_NAME = "breezeicons"

KOTLIN_FILE = (
    ROOT_DIR
    / MODULE_NAME
    / "src/main/java/com/github/migueldk17/breezeicons/icons/BreezeIcons.kt"
)
OUTPUT_FILE = (
    ROOT_DIR
    / MODULE_NAME
    / "src/main/java/com/github/migueldk17/breezeicons/icons/"
)

# -----------------------------
# Config
# -----------------------------

STYLES = [
    {
        "style": "Linear",
        "end": "object Outlined",
        "output": "LinearAll.generated.kt",
        "object_name": "BreezeIconsLinearAll"
    },
    {
        "style": "Outlined",
        "end": "object Colors",
        "output": "OutlinedAll.generated.kt",
        "object_name": "BreezeIconsOutlinedAll",
    },
    {
        "style": "Colors",
        "end": "}",
        "output": "ColorsAll.generated.kt",
        "object_name": "BreezeIconsColorsAll",
    }
]

# -----------------------------
# Guards
# -----------------------------
if not KOTLIN_FILE.exists():
    raise FileNotFoundError(
        "Arquivo não encontrado em: {}".format(KOTLIN_FILE)
        )

# -----------------------------
# Regex
# -----------------------------
CATEGORY_REGEX = re.compile(r'object\s+(\w+)\s*\{')
ICON_REGEX = re.compile(r'val\s+(\w+)\s*:\s*BreezeIconsType')

# -----------------------------
# Utils
# -----------------------------
def ok_symbol():
    try: 
        "✔".encode(sys.stdout.encoding or "otf-8")
        return "✔"
    except Exception:
        return "[OK]"

# -----------------------------
# Generator
# -----------------------------
def generate_all_for_style(style, end_maker, output_name, object_name):
    current_category = None
    icons = []
    inside_style = False

    
    lines = KOTLIN_FILE.read_text(encoding="utf-8").splitlines()

    for line in lines:
        # Enter style block
        if "object {}".format(style) in line:
            inside_style = True
            current_category = None
            continue

        # Exit style block
        if inside_style and end_maker in line:
            break
    
        if not inside_style:
            continue
        
        # Category (ignore the style object itself)
        category_match = CATEGORY_REGEX.search(line)
        if category_match:
            name = category_match.group(1)
            if name != style:
                current_category = name
            continue
        
        # Icon
        icon_match = ICON_REGEX.search(line)
        if icon_match and current_category:
            icons.append((icon_match.group(1), current_category))

        # Sort AFTER collecting everything
        icons.sort(key=lambda x: x[0])

        output_path = OUTPUT_FILE / output_name

        with output_path.open("w", encoding="utf-8") as f:
            f.write(
                "// AUTO-GENERATED FILE — DO NOT EDIT\n"
                "// Generated by script.py\n\n"
                "package com.github.migueldk17.breezeicons.icons\n\n"
                "import androidx.compose.runtime.Composable\n"
                "@Suppress(\"unused\")\n"
                "object {} {{".format(object_name)
            )

            for icon, category in icons:
                f.write(
                "           \n     val {}\n"
                "           @Composable\n"
                "           get() = BreezeIcons.{}.{}.{}".format(
                        icon, style, category, icon
                )
            )

            f.write("}\n")

        print("{} Generated {} icons in {}".format(
            ok_symbol(), len(icons), output_name
        ))

# -----------------------------
# Run
# -----------------------------
for cfg in STYLES:
        generate_all_for_style(
            style=cfg["style"],
            end_maker=cfg["end"],
            output_name=cfg["output"],
            object_name=cfg["object_name"],
        )
