import re
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent

MODULE_NAME = "breezeicons"

KOTLIN_FILE = (
    ROOT_DIR
    / MODULE_NAME
    / "src/main/java/com/github/migueldk17/breezeicons/icons/BreezeIcons.kt"
)
OUTPUT_FILE = (
    ROOT_DIR
    / MODULE_NAME
    / "src/main/java/com/github/migueldk17/breezeicons/icons/LinearAll.generated.kt"
)

if not KOTLIN_FILE.exists():
    raise FileNotFoundError(f"Arquivo não encontrado em: {KOTLIN_FILE}")

CATEGORY_REGEX = re.compile(r'object\s+(\w+)\s*\{')
ICON_REGEX = re.compile(r'val\s+(\w+)\s*:\s*BreezeIconsType')

current_category = None
icons = []
inside_linear = False

lines = KOTLIN_FILE.read_text(encoding="utf-8").splitlines()

for line in lines:
    if "object Linear" in line:
        inside_linear = True
        current_category = None
        continue
    
    if inside_linear and "object Colors" in line:
        break
    if inside_linear and "object Outlined" in line:
        break
    
    if not inside_linear:
        continue

    category_match = CATEGORY_REGEX.search(line)
    if category_match:
        current_category = category_match.group(1)
        continue

    icon_match = ICON_REGEX.search(line)
    if icon_match and current_category:
        icon_name = icon_match.group(1)
        icons.append((icon_name, current_category))

icons.sort(key=lambda x: x[0])

with OUTPUT_FILE.open("w", encoding="utf-8") as f:
    f.write(
        """// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by generate_linear_all.py

package com.github.migueldk17.breezeicons.icons

import androidx.compose.runtime.Composable

object LinearAll {

"""
    )

    for icon, category in icons:
        f.write(
            f"""        val {icon}
            @Composable
            get() = BreezeIcons.Linear.{category}.{icon}

"""
        )

    f.write("\n}\n")

print(f"✔ Generated {len(icons)} icons in LinearAll.generated.kt")
