package com.github.migueldk17.breezeicons.icons

/**
 * Enum class that lists all available icons in the BreezeIcons library.
 *
 * Each enum constant represents a unique icon and is used for logical identification and type safety
 * when working with BreezeIconsType.
 *
 * Use this enum to refer to specific icons programmatically, for example when setting an icon in the UI.
 */
enum class BreezeIconsEnum {

    //Icones Lineares
    BOOK_LINEAR,
    GROUP_LINEAR,
    CAR_LINEAR,
    CLOUD_LINEAR,
    GLOBE_LINEAR,
    AIRPLANE_LINEAR,
    DISCOVER_LINEAR,
    DROP_LINEAR,
    KEY_LINEAR,
    BUS_LINEAR,
    BAG2_LINEAR,
    CALENDAR_LINEAR,
    FACEBOOK_LINEAR,
    FORWARD_PLAYER_LINEAR,
    GAS_STATION_LINEAR,
    GOOGLE_LINEAR,
    GOOGLE_PLAY_LINEAR,
    VIDEO_CIRCLE_LINEAR,
    HOME_LINEAR,
    PAPERBIN_LINEAR,
    SETTINGS_LINEAR,
    LIKE_LINEAR,
    FORWARD_LINEAR,
    CHAT_SQUARE_LINEAR,
    EDIT_LINEAR,
    INFO_CIRCLE_LINEAR,
    AIRPODS_LINEAR,
    FILE_TEXT_LINEAR,
    HEADPHONES_ROUND_LINEAR,
    HOSPITAL_LINEAR,
    DOLLAR_CIRCLE_lINEAR,
    DOLLAR_SQUARE_LINEAR,
    MONEY_RECIVE_LINEAR,
    MONEY_SEND_LINEAR,
    MAGIC_PEN_LINEAR,
    DOCUMENT_LINEAR,
    NOTIFICATION_LINEAR,
    NOTIFICATION_BING_LINEAR,
    SPOTIFY_LINEAR,
    WHATSAPP_LINEAR,
    WINDOWS_LINEAR,
    ANDROID_LINEAR,

    //---------------icones outlined -------------------
    BAG_OUTLINED,
    BOOK_OUTLINED,
    CLOUD_OUTLINED,
    CALENDAR_OUTLINED,
    DISCOVERY_OUTLINED,
    DOLLAR_CIRCLE_OUTLINED,
    DOLLAR_SQUARE_OUTLINED,
    DROP_OUTLINED,
    FORWARD_OUTLINED,
    GLOBE_OUTLINED,
    GROUP_OUTLINED,
    HOSPITAL_OUTLINED,
    INFO_CIRCLE_OUTLINED,
    KEY_OUTLINED,
    LIKE_OUTLINED,
    MAGIC_PEN_OUTLINED,
    MONEY_RECIVE_OUTLINED,
    MONEY_SEND_OUTLINED,
    NOTIFICATION_OUTLINED,
    NOTIFICATION_BING_OUTLINED,
    PAPERBIN_OUTLINED,
    PLAY_CIRCLE_OUTLINED,
    SETTINGS_OUTLINED,




    //----------------icones Coloridos -------------------

    //-------------- icones vibrantes --------------------
    ICON_ORANGE_VIBRANT,
    ICON_YELLOW_VIBRANT,
    ICON_GREEN_VIBRANT,
    ICON_GREEN_CYAN_VIBRANT,
    ICON_TURQUOISE_VIBRANT,
    ICON_BLUE_VIBRANT,
    ICON_BLUE_ROYAL_VIBRANT,
    ICON_MAGENTA_VIBRANT,
    ICON_PINK_VIBRANT,
    ICON_PURPLE_VIBRANT,
    ICON_RED_VIBRANT,

    // Ícones soft
    ICON_SOFT_BLUE,
    ICON_SOFT_CYAN,
    ICON_SOFT_GREEN,
    ICON_SOFT_GREEN_CYAN,
    ICON_SOFT_MAGENTA,
    ICON_SOFT_ORANGE,
    ICON_SOFT_PINK,
    ICON_SOFT_PURPLE,
    ICON_SOFT_RED,
    ICON_SOFT_ROYAL_BLUE,
    ICON_SOFT_YELLOW,

    //Icone não especificado
    ICON_UNSPECIFIED
}