// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by script.py

package com.github.migueldk17.breezeicons.icons

import androidx.compose.runtime.Composable
@Suppress("unused")
object BreezeIconsLinearAll {           
     val AirplaneLinear
           @Composable
           get() = BreezeIcons.Linear.Mobility.AirplaneLinear           
     val Airpods
           @Composable
           get() = BreezeIcons.Linear.ElectronicDevices.Airpods           
     val AltArrowDown
           @Composable
           get() = BreezeIcons.Linear.Arrows.AltArrowDown           
     val AltArrowLeft
           @Composable
           get() = BreezeIcons.Linear.Arrows.AltArrowLeft           
     val AltArrowRight
           @Composable
           get() = BreezeIcons.Linear.Arrows.AltArrowRight           
     val AltArrowUp
           @Composable
           get() = BreezeIcons.Linear.Arrows.AltArrowUp           
     val AndroidLinear
           @Composable
           get() = BreezeIcons.Linear.Company.AndroidLinear           
     val Bag2
           @Composable
           get() = BreezeIcons.Linear.Shop.Bag2           
     val BookLinear
           @Composable
           get() = BreezeIcons.Linear.SchoolLearning.BookLinear           
     val BusLinear
           @Composable
           get() = BreezeIcons.Linear.Mobility.BusLinear           
     val CalendarLinear
           @Composable
           get() = BreezeIcons.Linear.Time.CalendarLinear           
     val CarLinear
           @Composable
           get() = BreezeIcons.Linear.Mobility.CarLinear           
     val CaseRoundMinimalistic
           @Composable
           get() = BreezeIcons.Linear.School.CaseRoundMinimalistic           
     val ChatLinear
           @Composable
           get() = BreezeIcons.Linear.Messages.ChatLinear           
     val ChefHat
           @Composable
           get() = BreezeIcons.Linear.FoodKitchen.ChefHat           
     val ChristmasTree
           @Composable
           get() = BreezeIcons.Linear.Nature.ChristmasTree           
     val CloudLinear
           @Composable
           get() = BreezeIcons.Linear.Weather.CloudLinear           
     val ConfettiMinimalistic
           @Composable
           get() = BreezeIcons.Linear.Essetional.ConfettiMinimalistic           
     val DiscoverLinear
           @Composable
           get() = BreezeIcons.Linear.Essetional.DiscoverLinear           
     val DocumentLinear
           @Composable
           get() = BreezeIcons.Linear.ContentEdit.DocumentLinear           
     val DollarCircle
           @Composable
           get() = BreezeIcons.Linear.Money.DollarCircle           
     val DollarSquare
           @Composable
           get() = BreezeIcons.Linear.Money.DollarSquare           
     val DropLinear
           @Composable
           get() = BreezeIcons.Linear.Weather.DropLinear           
     val EditLinear
           @Composable
           get() = BreezeIcons.Linear.Software.EditLinear           
     val FacebookLinear
           @Composable
           get() = BreezeIcons.Linear.Company.FacebookLinear           
     val FileText
           @Composable
           get() = BreezeIcons.Linear.Files.FileText           
     val ForwardLinear
           @Composable
           get() = BreezeIcons.Linear.VideoAudioImage.ForwardLinear           
     val Gamepad
           @Composable
           get() = BreezeIcons.Linear.ElectronicDevices.Gamepad           
     val GasStationLinear
           @Composable
           get() = BreezeIcons.Linear.Mobility.GasStationLinear           
     val GlobeLinear
           @Composable
           get() = BreezeIcons.Linear.Location.GlobeLinear           
     val GoogleLinear
           @Composable
           get() = BreezeIcons.Linear.Company.GoogleLinear           
     val GooglePlayLinear
           @Composable
           get() = BreezeIcons.Linear.Company.GooglePlayLinear           
     val GroupLinear
           @Composable
           get() = BreezeIcons.Linear.Delivery.GroupLinear           
     val Hanger
           @Composable
           get() = BreezeIcons.Linear.Essetional.Hanger           
     val HeadphonesRound
           @Composable
           get() = BreezeIcons.Linear.ElectronicDevices.HeadphonesRound           
     val Heart
           @Composable
           get() = BreezeIcons.Linear.Like.Heart           
     val HomeLinear
           @Composable
           get() = BreezeIcons.Linear.Building.HomeLinear           
     val Hospital
           @Composable
           get() = BreezeIcons.Linear.Building.Hospital           
     val InfoCircle
           @Composable
           get() = BreezeIcons.Linear.Essetional.InfoCircle           
     val KeyLinear
           @Composable
           get() = BreezeIcons.Linear.Security.KeyLinear           
     val Laptop
           @Composable
           get() = BreezeIcons.Linear.ElectronicDevices.Laptop           
     val LikeLinear
           @Composable
           get() = BreezeIcons.Linear.SupportLikeQuestion.LikeLinear           
     val MagicPen
           @Composable
           get() = BreezeIcons.Linear.DesignTools.MagicPen           
     val MenuDots
           @Composable
           get() = BreezeIcons.Linear.Essetional.MenuDots           
     val MoneyRecive
           @Composable
           get() = BreezeIcons.Linear.Money.MoneyRecive           
     val MoneySend
           @Composable
           get() = BreezeIcons.Linear.Money.MoneySend           
     val NotificationBingLinear
           @Composable
           get() = BreezeIcons.Linear.Notification.NotificationBingLinear           
     val NotificationLinear
           @Composable
           get() = BreezeIcons.Linear.Notification.NotificationLinear           
     val PaperBinLinear
           @Composable
           get() = BreezeIcons.Linear.Essetional.PaperBinLinear           
     val Recycle
           @Composable
           get() = BreezeIcons.Linear.Nature.Recycle           
     val Refresh
           @Composable
           get() = BreezeIcons.Linear.Arrows.Refresh           
     val Restart
           @Composable
           get() = BreezeIcons.Linear.Arrows.Restart           
     val SettingsLinear
           @Composable
           get() = BreezeIcons.Linear.Settings.SettingsLinear           
     val ShareLinear
           @Composable
           get() = BreezeIcons.Linear.Messages.ShareLinear           
     val Skirt
           @Composable
           get() = BreezeIcons.Linear.Essetional.Skirt           
     val Sleeping
           @Composable
           get() = BreezeIcons.Linear.Essetional.Sleeping           
     val SpotifyLinear
           @Composable
           get() = BreezeIcons.Linear.Company.SpotifyLinear           
     val SquareAcademicCap2
           @Composable
           get() = BreezeIcons.Linear.School.SquareAcademicCap2           
     val TShirt
           @Composable
           get() = BreezeIcons.Linear.Essetional.TShirt           
     val TeaCup
           @Composable
           get() = BreezeIcons.Linear.FoodKitchen.TeaCup           
     val TrafficEconomy
           @Composable
           get() = BreezeIcons.Linear.Essetional.TrafficEconomy           
     val Umbrella
           @Composable
           get() = BreezeIcons.Linear.Nature.Umbrella           
     val VerifiedCheck
           @Composable
           get() = BreezeIcons.Linear.Money.VerifiedCheck           
     val VideoCircleLinear
           @Composable
           get() = BreezeIcons.Linear.VideoAudioImage.VideoCircleLinear           
     val WhatsappLinear
           @Composable
           get() = BreezeIcons.Linear.Company.WhatsappLinear           
     val WindowsLinear
           @Composable
           get() = BreezeIcons.Linear.Company.WindowsLinear}
