// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by script.py

package com.github.migueldk17.breezeicons.icons

import androidx.compose.runtime.Composable
@Suppress("unused")
object BreezeIconsOutlinedAll {           
     val Bag
           @Composable
           get() = BreezeIcons.Outlined.Shop.Bag           
     val Book
           @Composable
           get() = BreezeIcons.Outlined.SchoolLearning.Book           
     val Calendar
           @Composable
           get() = BreezeIcons.Outlined.Time.Calendar           
     val ChatRound
           @Composable
           get() = BreezeIcons.Outlined.MessagesConversation.ChatRound           
     val Cloud
           @Composable
           get() = BreezeIcons.Outlined.Weather.Cloud           
     val Discover
           @Composable
           get() = BreezeIcons.Outlined.Essetional.Discover           
     val DollarCircle
           @Composable
           get() = BreezeIcons.Outlined.Money.DollarCircle           
     val DollarSquare
           @Composable
           get() = BreezeIcons.Outlined.Money.DollarSquare           
     val Drop
           @Composable
           get() = BreezeIcons.Outlined.Weather.Drop           
     val Export
           @Composable
           get() = BreezeIcons.Outlined.Arrow.Export           
     val ForwardLinear
           @Composable
           get() = BreezeIcons.Outlined.VideoAudioImage.ForwardLinear           
     val Globe
           @Composable
           get() = BreezeIcons.Outlined.Location.Globe           
     val Group
           @Composable
           get() = BreezeIcons.Outlined.Delivery.Group           
     val Heart
           @Composable
           get() = BreezeIcons.Outlined.SupportLikeQuestion.Heart           
     val Hospital
           @Composable
           get() = BreezeIcons.Outlined.Building.Hospital           
     val InfoCircle
           @Composable
           get() = BreezeIcons.Outlined.Essetional.InfoCircle           
     val Key
           @Composable
           get() = BreezeIcons.Outlined.Security.Key           
     val Like
           @Composable
           get() = BreezeIcons.Outlined.SupportLikeQuestion.Like           
     val Logout
           @Composable
           get() = BreezeIcons.Outlined.Arrow.Logout           
     val MagicPen
           @Composable
           get() = BreezeIcons.Outlined.DesignTools.MagicPen           
     val MoneyRecive
           @Composable
           get() = BreezeIcons.Outlined.Money.MoneyRecive           
     val MoneySend
           @Composable
           get() = BreezeIcons.Outlined.Money.MoneySend           
     val Notification
           @Composable
           get() = BreezeIcons.Outlined.Notification.Notification           
     val NotificationBing
           @Composable
           get() = BreezeIcons.Outlined.Notification.NotificationBing           
     val PaperBin
           @Composable
           get() = BreezeIcons.Outlined.Essetional.PaperBin           
     val Pen
           @Composable
           get() = BreezeIcons.Outlined.MessagesConversation.Pen           
     val Repeat
           @Composable
           get() = BreezeIcons.Outlined.Arrow.Repeat           
     val Settings
           @Composable
           get() = BreezeIcons.Outlined.Settings.Settings           
     val Star
           @Composable
           get() = BreezeIcons.Outlined.SupportLikeQuestion.Star           
     val VideoCircle
           @Composable
           get() = BreezeIcons.Outlined.VideoAudioImage.VideoCircle}
